receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  logging:
    loglevel: warn
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:9464

processors:
  batch: {}
  memory_limiter:
    check_interval: 2s
    limit_mib: 512

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/jaeger, logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
